= Get a Managed OpenShift Cluster
include::_attributes.adoc[]

[#orientation]
== Do you already have a Managed OpenShift Cluster?

[tabs]
====
Yes::
+
--
If you already have a cluster, you should read the summarized xref:#cluster-requirements[cluster requirements] below.

If you are certain that your cluster meets all these requirement, you can skip straight to the "xref:03-rhods.adoc[Get RHODS]" section.
--
No::
+
--
If you don't yet have a Managed OpenShift Cluster, you will need to keep reading this page in order to:

* Be aware of the xref:#cluster-requirements[cluster requirements]
* Choose between xref:#chooseOSDROSA[ROSA and OSD]
* Decide if you want to use the 60-day xref:#chooseOSDROSA[OSD Trial]
--
====

[#cluster-requirements]
== Managed OpenShift Cluster Requirement for RHODS

* It has to be a **Managed** OpenShift:
** either ROSA or OSD
** not a general OCP cluster
* It has to be on **AWS**
** It cannot be an on-prem cluster
** Currently only AWS is supported
* You need to have access to both:
** the link:https://console.redhat.com/[Red Hat Hybrid Console]
** the OpenShift Web Console of your cluster
* The version of OpenShift needs to be
** OpenShift 4.9 or higher
* If you are using ROSA, ensure that the cluster was **NOT** deployed with the `--sts` option
* OpenShift Authentication needs to be configured

[#redhataccount]
== About your RedHat.com account

* Whether you use OSD or ROSA, you will need to link:https://www.redhat.com/wapps/ugc/register.html[sign up for a Red Hat login].
* When you do, there are two types of account: **Corporate** or **Personal**.
* It is very likely that your organization already has a Corporate Account with Red Hat.
** If that is the case, you should ask to be granted access to it.
* If your organization does not yet have an account, you should create a **Corporate** one even if you will be the only person using these resources. It makes sharing the work and transferring ownership of environments much more straightforward.


[#chooseOSDROSA]
== Choosing between ROSA and OSD

CAUTION: Under construction

If you need more information on how to choose between OSD and ROSA, please consult these resources.

.Comparison of ROSA and OSD
[options="header,footer"]
|=======================
|Topic|ROSA |OSD |
|Main Page|https://cloud.redhat.com/products/amazon-openshift[Red Hat OpenShift Service on AWS (ROSA)] |https://cloud.redhat.com/products/dedicated/[OpenShift Dedicated (OSD)] |
|Service Type|Managed|Managed|
|=======================

[#OSDTrial]
== OSD Trial

An OSD Trial Cluster allows you to test a 40-vCPU OSD cluster for 60 days.

Note that you are responsible for the Cloud Infrastructure Costs of the trial.

If you are interested in signing up for an OSD Trials, please read carefully the content of the "link:https://access.redhat.com/articles/5990101[About the OpenShift Dedicated Trial]" page.



// [cols="1,1"]
// |===
// |Cell in column 1, row 1
// |Cell in column 2, row 1

// |Cell in column 1, row 2
// |Cell in column 2, row 2

// |Cell in column 1, row 3
// |Cell in column 2, row 3
// |===

