= Common Customizations (optional)

CAUTION: Under construction.

CAUTION: this is still a draft

[#autoscaling]
== Using auto-scaling Machine Pools

Using Auto-Scaling Machine Pools allows your environment to grow and shrink based on usage.

    https://docs.openshift.com/rosa/nodes/nodes-about-autoscaling-nodes.html

[#rhodsaccess]
== Restrict Access to RHODS to only a few users

Any user who can log into OpenShift can also use RHODS. If you want to restrict RHODS access to only specific OpenShift Users, you can consult the link:https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/1/html/managing_users_and_user_resources/adding-users-for-openshift-data-science_useradd[documentation on how to add users].

[#selfprovision]
== Restrict OpenShift Self-Provisionning to RHODS users

Most OpenShift environments are configured in such a way that users who can authenticate to OpenShift also have the "self-provisionner" role. +
This can be great for developpers, but might be too much if there are many potential users. +
A fairly standard OpenShift practice is to reduce the number of users who have this ability. +
Consult link:https://docs.openshift.com/container-platform/4.9/applications/projects/configuring-project-creation.html#disabling-project-self-provisioning_configuring-project-creation[the documentation on disabling project self-provisioning] for more info.

// [#notebooksizes]
// == Changing the size of the available notebooks

// [#culling]
// == Notebook Culling
